apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: k8s-practice
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    minReadySeconds: 30
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 1
    selector:
      matchLabels:
        app: frontend-app
    template:
      metadata: 
        name: frontend-app
        labels:
          app: frontend-app
      spec:
        securityContext:
          runAsUser: 1000
          fsGroup: 1000
        containers:
        - name: frontend-container
          labels:
            app: 
          image: vnr1986/springmango:1
          ports:
          - containerPort: 8080
          env:
          - name: MONGO_DB_HOSTNAME
            value: backend-svc
          - name: MONGO_DB_USERNAME
            valueFrom:
              secret:
                name: backend-secret
                key: mongo_db_username
          - name: MONGO_DB_PASSWORD
            valueFrom:
              secret:
                name: backend-secret
                key: mongo_db_password
          resources:
            request:
              cpu: 200m
              memory: 64Mi
           limits:
             cpu: 210m
             memory: 64Mi

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: k8s-practice
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
  - port: 80
    targetPort:
    nodePort: 30010



















