apiVersion: apps/v1
kind: Deployment
metadata:
  name: backenddeployment
  namespace: k8s-practice
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector: 
    matchLabels:
      app: backendapp
  template:
    metadata: 
      name: backendapp
      labels:
        app: backendapp
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: backendpvc 
      containers: 
      - name: backendcontainer
        image: mongo
        ports:
        - containerPort: 27017
        env: 
        - name: MONGO_INITDB_ROOT_USERNAME 
          valueFrom:
            secretKeyRef: 
              name: mdbsecret
              key: mdb_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mdbsecret
              key: mdb_password
        volumeMounts:
        - name: pvc
          mountPath: /data/db
---

apiVersion: v1
kind: Service
metadata:
  name: backendsvc
  namespace: k8s-practice
spec:
  type: ClusterIP
  selector:
    app: backendapp
  ports:
  - port: 27017
    targetPort: 27017
