apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backendpvc
  namespace: k8s-practice
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: nfs-storageclass

