apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: frontenddeployment
  namespace: k8s-practice
spec: 
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: frontendapp
  template:
    metadata: 
      name: frontendapp
      labels:
        app: frontendapp
    spec:
      containers:
      - name: frontendcontainer
        image: vnr1986/springmango:1
        ports:
        - containerPort: 8080
        resources: 
          requests:
            cpu: 100m
            memory: 64Mi  
        env:
        - name: MONGO_DB_HOSTNAME 
          value: backendsvc
        - name: MONGO_DB_USERNAME 
          valueFrom:
            secretKeyRef: 
              name: mdbsecret
              key: mdb_username              
        - name: MONGO_DB_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mdbsecret
              key: mdb_password
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3       
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080

---

apiVersion: v1
kind: Service
metadata: 
  name: frontendsvc
  namespace: k8s-practice
spec: 
  type: NodePort
  selector:
    app: frontendapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001
