apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sbadep
  namespace: k8s-practice
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: sbapod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      name: sbapod
      labels:
        app: sbapod
    spec:
      containers:
      - name: sbacont
        image: vnr1986/springmango:1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: mdbsvc
        - name: MONGO_DB_USERNAME
          value: devdb
        - name: MONGO_DB_PASSWORD
          value: devdb@123

---

apiVersion: v1
kind: Service
metadata:
  name: spasvc
  namespace: k8s-practice
spec:
  type: NodePort
  selector:
    app: sbapod
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30002


